requires 'perl', '5.18.2';

requires "App::Sqitch", ">= 0.992";
requires "Catalyst";
requires "Catalyst::Action::RenderView";
requires "Catalyst::ActionRole::ACL";
requires "Catalyst::Component::InstancePerContext";
requires "Catalyst::Authentication::Store::DBIx::Class";
requires "Catalyst::Plugin::Authentication";
requires "Catalyst::Plugin::Authorization::ACL";
requires "Catalyst::Plugin::Authorization::Roles";
requires "Catalyst::Plugin::ConfigLoader";
requires "Catalyst::Plugin::I18N";
requires "Catalyst::Plugin::RedirectAndDetach";
requires "Catalyst::Plugin::Session";
requires "Catalyst::Plugin::Session::State::Cookie";
requires "Catalyst::Plugin::Session::Store::DBIC";
requires "Catalyst::Plugin::Session::PerUser";
requires "Catalyst::Plugin::Static::Simple";
requires "Catalyst::Plugin::StatusMessage";
requires "Catalyst::TraitFor::Request::XMLHttpRequest";
requires "Catalyst::View::CSV";
requires "Catalyst::View::JSON";
requires "Catalyst::View::TT";
requires "Clone";
requires "Config::General";
requires "Crypt::Eksblowfish::Bcrypt";
requires "Crypt::CBC";
requires "Crypt::OpenSSL::AES";
requires "DateTime";
requires "DateTime::Format::Strptime";
requires "DateTime::Format::Pg";
requires "DateTime::TimeZone";
requires "DBD::Pg", ">= 3.0.0";
requires "DBI";
requires "DBIx::Class";
requires "DBIx::Class::EncodedColumn";
requires "DBIx::Class::FilterColumn";
requires "DBIx::Class::Helper::Row::ToJSON";
requires "DBIx::Class::InflateColumn::DateTime::Duration";
requires "DBIx::Class::Schema::Loader";
requires "DBIx::Class::TimeStamp";
requires "DBM::Deep";
requires "Data::Printer";
requires "DateTimeX::Easy";
requires "Digest::PBKDF2", ">= 0.010";
requires "Email::Valid";
requires "Encode";
requires "Encode::Guess";
requires "Geo::Coder::Google";
requires "HTML::FormHandler";
requires "HTML::FormHandler::Model::DBIC";
requires "HTML::Selector::XPath";
requires "IO::All";
requires "Image::Magick", "6.77, < 6.82";
requires "JSON::XS";
requires "Lingua::Conjunction";
requires "Log::Log4perl";
requires "Log::Log4perl::Catalyst";
requires "LWP::Protocol::https";
requires "LWP::UserAgent";
requires "List::AllUtils";
requires "List::MoreUtils";
requires "List::Util", ">= 1.31";
requires "Mail::Address";
requires "Module::Runtime", ">= 0.014";
requires "Moose", ">= 2.1203";
requires "Moose::Exporter";
requires "MooseX::MarkAsMethods", ">= 0.13";
requires "MooseX::MethodAttributes";
requires "MooseX::NonMoose", ">= 0.16";
requires "MooseX::Role::Parameterized";
requires "MooseX::Role::WithOverloading";
requires "MooseX::StrictConstructor";
requires "MooseX::Types::Common::String";
requires "Net::Domain::TLD";
requires "Net::DNS";
requires "Parallel::ForkManager";
requires "Plack";
requires "Plack::App::File";
requires "Plack::Builder";
requires "Plack::Util";
requires "Spiffy";
requires "Sys::Hostname";
requires "Sys::Hostname::Long";
requires "Test::Base";
requires "Test::Class::Most";
requires "Test::Moose";
requires "Text::CSV::Encoded";
requires "Text::CSV_XS";
requires "Try::Tiny";
requires "URI";
requires "Web::Scraper";
requires "aliased";
requires "local::lib";
requires "namespace::autoclean", ">= 0.09";
requires "parent";
requires "warnings::everywhere";
