#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "nginx"
cookbook "uwsgi"
cookbook "postgresql",
    :git => "https://github.com/phlipper/chef-postgresql"
cookbook "nodejs"
cookbook "npm"
cookbook "el",
    :path => "site/el"
cookbook "users"
cookbook "sudo"
